import mongoose from 'mongoose';

const projectSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true
    },
    projectName: {
      type: String,
      required: [true, 'Please provide a project name'],
      trim: true,
      maxlength: [100, 'Project name cannot exceed 100 characters']
    },
    sourceType: {
      type: String,
      required: true,
      enum: ['zip', 'github']
    },
    githubUrl: {
      type: String,
      default: '',
      trim: true
    },
    zipFile: {
      type: String,
      default: ''
    },
    extractedPath: {
      type: String,
      default: '' // Path on disk to the extracted folder structure
    },
    status: {
      type: String,
      enum: ['pending', 'analyzing', 'completed', 'failed'],
      default: 'pending',
      index: true
    },
    techStack: {
      type: [String],
      default: []
    },
    // The master structured JSON knowledge representation parsed by our static code analyzer
    analysisContext: {
      type: Object,
      default: null
    },
    // The final high-fidelity human-readable texts generated by Google Gemini AI / Fallback compiler
    aiContext: {
      type: Object,
      default: null
    }
  },
  {
    timestamps: true
  }
);

const Project = mongoose.model('Project', projectSchema);

export default Project;
